# Generated by Django 5.1.2 on 2024-11-16 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blogpost_image_blogpost_preview_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-views_count'], 'verbose_name': 'Блог', 'verbose_name_plural': 'Блог'},
        ),
    ]
